#!/bin/#!/usr/bin/env bash

set -eux -o pipefail

JENKINS_URL=${JENKINS_URL:-http://jenkins:8080/jenkins}
JENKINS_ADMIN_USER=${JENKINS_ADMIN_USER:-butler}
JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD:-butler}
GITSERVER_URL=${EXTERNAL_URL}
GITSERVER_API_URL="${GITSERVER_URL}/api/v1"
GITSERVER_ADMIN_USER=${GITSERVER_ADMIN_USER:-butler}
GITSERVER_ADMIN_PASSWORD=${GITSERVER_ADMIN_PASSWORD:-butler}
TIME_TO_WAIT=5

set +e
#### Waiting for Jenkins to be ready
while true; do
  HTTP_RESULT="$(curl --output /dev/null --write-out '%{http_code}\n' \
    --silent -L -u "${JENKINS_ADMIN_USER}:${JENKINS_ADMIN_PASSWORD}"\
     "${JENKINS_URL}/credentials")"

  [ "${HTTP_RESULT}" -eq 200 ] && break \
    || echo "Got HTTP code ${HTTP_RESULT} from Jenkins. Waiting ${TIME_TO_WAIT}s before retrying"

  sleep "${TIME_TO_WAIT}"
done

#### Waiting for the Gitserver to start and having the user ready
while true; do
  curl -u "${GITSERVER_ADMIN_USER}:${GITSERVER_ADMIN_PASSWORD}" \
      --fail "${GITSERVER_API_URL}/user" \
  && break || \
    echo "Gitserver still not started, waiting ${TIME_TO_WAIT}s before retrying"

  sleep "${TIME_TO_WAIT}"
done
set -e

# Get the publickey generated by BlueOcean for our user in jenkins
PUBLIC_KEY="$(curl -sSL -u "${JENKINS_ADMIN_USER}:${JENKINS_ADMIN_PASSWORD}" \
  "${JENKINS_URL}/blue/rest/organizations/jenkins/user/publickey/" \
  | jq -r '.publickey')"

# Automatically add this key to the GitServer
curl -v -X POST -s \
  -u "${GITSERVER_ADMIN_USER}:${GITSERVER_ADMIN_PASSWORD}" \
  -F "title=blueocean-generated-key" \
  -F "key=${PUBLIC_KEY}" \
  ${GITSERVER_API_URL}/user/keys

echo "== Blue Ocean Key added to Gitea"
exit 0
