#!/bin/bash

set -ex

write_key() {
	mkdir -p "${JENKINS_AGENT_HOME}/.ssh"
	echo "$1" > "${JENKINS_AGENT_HOME}/.ssh/authorized_keys"
	chown -Rf jenkins:jenkins "${JENKINS_AGENT_HOME}/.ssh"
	chmod 0700 -R "${JENKINS_AGENT_HOME}/.ssh"
}

set_ssh_env() {
  mkdir -p "${JENKINS_AGENT_HOME}/.ssh"
  echo 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' \
    | tee "${JENKINS_AGENT_HOME}/.ssh/environment"
}

if [[ $JENKINS_SLAVE_SSH_PUBKEY == ssh-* ]]; then
  write_key "${JENKINS_SLAVE_SSH_PUBKEY}"
fi
if [[ $# -gt 0 ]]; then
  if [[ $1 == ssh-* ]]; then
    write_key "$1"
    shift 1
  else
    exec "$@"
  fi
fi
set_ssh_env
ssh-keygen -A

nohup bash dockerd-entrypoint.sh --bip 192.168.0.1/24 &> /dev/stdout&
exec /usr/sbin/sshd -D -e "${@}"
